// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistency;

namespace Persistency.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210628212426_Notat")]
    partial class Notat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Domain.Nota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nota_Std")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentiId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notat");
                });
#pragma warning restore 612, 618
        }
    }
}
