// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistency;

namespace Persistency.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Domain.Nota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nota_Std")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentiId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentiId");

                    b.ToTable("Notat");
                });

            modelBuilder.Entity("Domain.Studenti", b =>
                {
                    b.Property<Guid>("StudentiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Drejtimi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mbiemri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Niveli")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentiId");

                    b.ToTable("Studentet");
                });

            modelBuilder.Entity("Domain.Nota", b =>
                {
                    b.HasOne("Domain.Studenti", "Studenti")
                        .WithMany("Nota")
                        .HasForeignKey("StudentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studenti");
                });

            modelBuilder.Entity("Domain.Studenti", b =>
                {
                    b.Navigation("Nota");
                });
#pragma warning restore 612, 618
        }
    }
}
